export interface KeyType {
    key: String,
    code: String,
    keyCode: Number,
    which: Number,
    purpose: String
}

export const modifiers:any = {
    ctrl: "Control",
    alt: "Alt",
    shift: "Shift",
    meta: "Meta",
}

// Понимаю, что вариантов конечно гораздо больше,
// но т.к. это тестовое задание, делать полноценное исследование нет смысла
export const keys = [
    { key: "Backspace",   code: "Backspace",      keyCode: 8,    which: 8,    purpose: "control"  },
    { key: "Tab",         code: "Tab",            keyCode: 9,    which: 9,    purpose: "control"  },
    { key: "Enter",       code: "Enter",          keyCode: 13,   which: 13,   purpose: "control" },
    { key: "Enter",       code: "NumpadEnter",    keyCode: 13,   which: 13,   purpose: "numpad" },
    { key: "Shift",       code: "ShiftLeft",      keyCode: 16,   which: 16,   purpose: "modifier" },
    { key: "Shift",       code: "ShiftRight",     keyCode: 16,   which: 16,   purpose: "modifier" },
    { key: "Control",     code: "ControlLeft",    keyCode: 17,   which: 17,   purpose: "modifier" },
    { key: "Control",     code: "ControlRight",   keyCode: 17,   which: 17,   purpose: "modifier" },
    { key: "Alt",         code: "AltLeft",        keyCode: 18,   which: 18,   purpose: "modifier" },
    { key: "Alt",         code: "AltRight",       keyCode: 18,   which: 18,   purpose: "modifier" },
    { key: "Pause",       code: "Pause",          keyCode: 19,   which: 19,   purpose: "control" },
    { key: "CapsLock",    code: "CapsLock",       keyCode: 20,   which: 20,   purpose: "control" },
    { key: "Escape",      code: "Escape",         keyCode: 27,   which: 27,   purpose: "control" },
    { key: "Space",       code: "Space",          keyCode: 32,   which: 32,   purpose: "symbol" },
    { key: "PageUp",      code: "PageUp",         keyCode: 33,   which: 33,   purpose: "control" },
    { key: "PageDown",    code: "PageDown",       keyCode: 34,   which: 34,   purpose: "control" },
    { key: "End",         code: "End",            keyCode: 35,   which: 35,   purpose: "control" },
    { key: "Home",        code: "Home",           keyCode: 36,   which: 36,   purpose: "control" },
    { key: "ArrowLeft",   code: "ArrowLeft",      keyCode: 37,   which: 37,   purpose: "control" },
    { key: "ArrowUp",     code: "ArrowUp",        keyCode: 38,   which: 38,   purpose: "control" },
    { key: "ArrowRight",  code: "ArrowRight",     keyCode: 39,   which: 39,   purpose: "control" },
    { key: "ArrowDown",   code: "ArrowDown",      keyCode: 40,   which: 40,   purpose: "control" },
    { key: "PrintScreen", code: "PrintScreen",    keyCode: 44,   which: 44,   purpose: "control" },
    { key: "Insert",      code: "Insert",         keyCode: 45,   which: 45,   purpose: "control" },
    { key: "Delete",      code: "Delete",         keyCode: 46,   which: 46,   purpose: "control" },
    { key: "0",           code: "Digit0",         keyCode: 48,   which: 48,   purpose: "symbol" },
    { key: "1",           code: "Digit1",         keyCode: 49,   which: 49,   purpose: "symbol" },
    { key: "2",           code: "Digit2",         keyCode: 50,   which: 50,   purpose: "symbol" },
    { key: "3",           code: "Digit3",         keyCode: 51,   which: 51,   purpose: "symbol" },
    { key: "4",           code: "Digit4",         keyCode: 52,   which: 52,   purpose: "symbol" },
    { key: "5",           code: "Digit5",         keyCode: 53,   which: 53,   purpose: "symbol" },
    { key: "6",           code: "Digit6",         keyCode: 54,   which: 54,   purpose: "symbol" },
    { key: "7",           code: "Digit7",         keyCode: 55,   which: 55,   purpose: "symbol" },
    { key: "8",           code: "Digit8",         keyCode: 56,   which: 56,   purpose: "symbol" },
    { key: "9",           code: "Digit9",         keyCode: 57,   which: 57,   purpose: "symbol" },
    { key: "a",           code: "KeyA",           keyCode: 65,   which: 65,   purpose: "symbol" },
    { key: "b",           code: "KeyB",           keyCode: 66,   which: 66,   purpose: "symbol" },
    { key: "c",           code: "KeyC",           keyCode: 67,   which: 67,   purpose: "symbol" },
    { key: "d",           code: "KeyD",           keyCode: 68,   which: 68,   purpose: "symbol" },
    { key: "e",           code: "KeyE",           keyCode: 69,   which: 69,   purpose: "symbol" },
    { key: "f",           code: "KeyF",           keyCode: 70,   which: 70,   purpose: "symbol" },
    { key: "g",           code: "KeyG",           keyCode: 71,   which: 71,   purpose: "symbol" },
    { key: "h",           code: "KeyH",           keyCode: 72,   which: 72,   purpose: "symbol" },
    { key: "i",           code: "KeyI",           keyCode: 73,   which: 73,   purpose: "symbol" },
    { key: "j",           code: "KeyJ",           keyCode: 74,   which: 74,   purpose: "symbol" },
    { key: "k",           code: "KeyK",           keyCode: 75,   which: 75,   purpose: "symbol" },
    { key: "l",           code: "KeyL",           keyCode: 76,   which: 76,   purpose: "symbol" },
    { key: "m",           code: "KeyM",           keyCode: 77,   which: 77,   purpose: "symbol" },
    { key: "n",           code: "KeyN",           keyCode: 78,   which: 78,   purpose: "symbol" },
    { key: "o",           code: "KeyO",           keyCode: 79,   which: 79,   purpose: "symbol" },
    { key: "p",           code: "KeyP",           keyCode: 80,   which: 80,   purpose: "symbol" },
    { key: "q",           code: "KeyQ",           keyCode: 81,   which: 81,   purpose: "symbol" },
    { key: "r",           code: "KeyR",           keyCode: 82,   which: 82,   purpose: "symbol" },
    { key: "s",           code: "KeyS",           keyCode: 83,   which: 83,   purpose: "symbol" },
    { key: "t",           code: "KeyT",           keyCode: 84,   which: 84,   purpose: "symbol" },
    { key: "u",           code: "KeyU",           keyCode: 85,   which: 85,   purpose: "symbol" },
    { key: "v",           code: "KeyV",           keyCode: 86,   which: 86,   purpose: "symbol" },
    { key: "w",           code: "KeyW",           keyCode: 87,   which: 87,   purpose: "symbol" },
    { key: "x",           code: "KeyX",           keyCode: 88,   which: 88,   purpose: "symbol" },
    { key: "y",           code: "KeyY",           keyCode: 89,   which: 89,   purpose: "symbol" },
    { key: "z",           code: "KeyZ",           keyCode: 90,   which: 90,   purpose: "symbol" },
    { key: "Meta",        code: "MetaLeft",       keyCode: 91,   which: 91,   purpose: "modifier" },
    { key: "Meta",        code: "MetaRight",      keyCode: 92,   which: 92,   purpose: "modifier" },
    { key: "0",           code: "Numpad0",        keyCode: 96,   which: 96,   purpose: "numpad" },
    { key: "1",           code: "Numpad1",        keyCode: 97,   which: 97,   purpose: "numpad" },
    { key: "2",           code: "Numpad2",        keyCode: 98,   which: 98,   purpose: "numpad" },
    { key: "3",           code: "Numpad3",        keyCode: 99,   which: 99,   purpose: "numpad" },
    { key: "4",           code: "Numpad4",        keyCode: 100,  which: 100,  purpose: "numpad" },
    { key: "5",           code: "Numpad5",        keyCode: 101,  which: 101,  purpose: "numpad" },
    { key: "6",           code: "Numpad6",        keyCode: 102,  which: 102,  purpose: "numpad" },
    { key: "7",           code: "Numpad7",        keyCode: 103,  which: 103,  purpose: "numpad" },
    { key: "8",           code: "Numpad8",        keyCode: 104,  which: 104,  purpose: "numpad" },
    { key: "9",           code: "Numpad9",        keyCode: 105,  which: 105,  purpose: "numpad" },
    { key: "*",           code: "NumpadMultiply", keyCode: 106,  which: 106,  purpose: "numpad" },
    { key: "+",           code: "NumpadAdd",      keyCode: 107,  which: 107,  purpose: "numpad" },
    { key: "-",           code: "NumpadSubtract", keyCode: 109,  which: 109,  purpose: "numpad" },
    { key: ".",           code: "NumpadDecimal",  keyCode: 110,  which: 110,  purpose: "numpad" },
    { key: "/",           code: "NumpadDivide",   keyCode: 111,  which: 111,  purpose: "numpad" },
    { key: "F1",          code: "F1",             keyCode: 112,  which: 112,  purpose: "control" },
    { key: "F2",          code: "F2",             keyCode: 113,  which: 113,  purpose: "control" },
    { key: "F3",          code: "F3",             keyCode: 114,  which: 114,  purpose: "control" },
    { key: "F4",          code: "F4",             keyCode: 115,  which: 115,  purpose: "control" },
    { key: "F5",          code: "F5",             keyCode: 116,  which: 116,  purpose: "control" },
    { key: "F6",          code: "F6",             keyCode: 117,  which: 117,  purpose: "control" },
    { key: "F7",          code: "F7",             keyCode: 118,  which: 118,  purpose: "control" },
    { key: "F8",          code: "F8",             keyCode: 119,  which: 119,  purpose: "control" },
    { key: "F9",          code: "F9",             keyCode: 120,  which: 120,  purpose: "control" },
    { key: "F10",         code: "F10",            keyCode: 121,  which: 121,  purpose: "control" },
    { key: "F11",         code: "F11",            keyCode: 122,  which: 122,  purpose: "control" },
    { key: "F12",         code: "F12",            keyCode: 123,  which: 123,  purpose: "control" },
    { key: "NumLock",     code: "NumLock",        keyCode: 144,  which: 144,  purpose: "control" },
    { key: "ScrollLock",  code: "ScrollLock",     keyCode: 145,  which: 145,  purpose: "control" },
    { key: ";",           code: "Semicolon",      keyCode: 186,  which: 186,  purpose: "symbol" },
    { key: "=",           code: "Equal",          keyCode: 187,  which: 187,  purpose: "symbol" },
    { key: ",",           code: "Comma",          keyCode: 188,  which: 188,  purpose: "symbol" },
    { key: "-",           code: "Minus",          keyCode: 189,  which: 189,  purpose: "symbol" },
    { key: ".",           code: "Period",         keyCode: 190,  which: 190,  purpose: "symbol" },
    { key: "/",           code: "Slash",          keyCode: 191,  which: 191,  purpose: "symbol" },
    { key: "`",           code: "Backquote",      keyCode: 192,  which: 192,  purpose: "symbol" },
    { key: "[",           code: "BracketLeft",    keyCode: 219,  which: 219,  purpose: "symbol" },
    { key: "\\",          code: "Backslash",      keyCode: 220,  which: 220,  purpose: "symbol" },
    { key: "]",           code: "BracketRight",   keyCode: 221,  which: 221,  purpose: "symbol" },
    { key: "'",           code: "Quote",          keyCode: 222,  which: 222,  purpose: "symbol" },
]